### PR TITLE
Update HttpServer logic

### PR DESCRIPTION
**Pull request by archofthings**
Hi Behnam!
I Updated server logic to return 404 when no route exists, based on previous PR.

### CODE REVIEW

**Comment by benyblack** [comment]
Since this is a change in the logic and the features plz update the readme and also the version number to 0.5.0.

**Comment by benyblack** [comment]
Don't forget to update the description in nuspec and csproj.

**Comment by archofthings** [comment]
All done.

**Comment by benyblack** [comment]
Thanks for the perfect code.

**Pull request merged**
